name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create build
        working-directory: ./website
        run: npm --force ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRCDATASETCOLAB }}'
          channelId: live
          projectId: frcdatasetcolab
          enteryPoint: ./website
